server:
  port: 8080
  charset: UTF-8
  disablePathCorrection: false
  enablePathEscape: false
  fireMethodNotAllowed: false
  disableBodyConsumptionOnUnmarshal: false

mysql:
  dsn: "xiaoju:Zj$741943@tcp(10.96.84.241:3306)/scenter?timeout=500ms&readTimeout=300ms&writeTimeout=500ms&loc=Local&parseTime=true"
  maxIdConn: 100
  maxOpenConn: 300